sudo: required

language: bash

env:
  DOCKER_COMPOSE_VERSION: 1.4.2

services:
  - docker

before_install:
  - echo $USER
  - docker run --rm -v $(pwd):/app composer install
  #- sudo chown -R $USER:$USER ./
  - cp .env.travis .env
  - cp docker-compose.yml.travis docker-compose.yml
  - touch ./storage/logs/laravel.log

script:
  - docker-compose up -d
  - docker-compose ps
  - docker-compose exec app ls -la storage/logs/
  - docker-compose exec app whoami
